/*
package com.sachtech.datingapp.utils

object PrefKeys{
    val PREF_MARRIAGE_PLANS: String="prefMarriagePlans"
    val PREF_LIFE_AFTER_MARRIAGE: String="prefLifeAfterMarriage"
    val PREF_PRAYS: String="prefPrays"
    val PREF_HALAL: String="prefHalal"
    val PREF_WEAR: String="prefWear"
    val PREF_BEARD: String="prefBeard"
    val PREF_REVERT: String="prefRevert"
    val PREF_QURAN: String="prefQuran"
    val SWIPECOUNT: String="swipeCount"
    val PREF_EDUCATION: String="prefEducation"
    val PREF_PROFESSION: String="prefProfession"
    val PREF_HAIRCOLOR: String="prefHairColor"
    val PREF_COLORCOMPLEXION: String="prefColorComplexion"
    val PREF_EYECOLOR: String="prefEyeColor"
    val PREF_ORIGIN: String="prefOrigin"
    val LOCATION: String="location"
    val USERPREFS: String="user_preferences"
    val PASSWORD: String="password"
    val EMAIL: String="email"
    val USERNAME: String="user_name"
    val ALLUSERS: String="all_users"
    val LANGUAGE: String="language"
    val SELECTEDUSER: String="selected_user"
    val SELECTEDCHATUSER: String="selected_chat_user"
    const val COMETUSER: String="comet_user"
    const val LATITUDE: String="latitude"
    const val LONGITUDE: String="longitude"
    const val NATIONALITY: String="nationality"
    const val EDUCATION: String="education"
    val PROFESSION: String="profession"
    val EYECOLOR: String="eye_color"
    val HAIRCOLOR: String="hair_color"
    val COLORCOMPLEXION: String="color_complexion"
    val ORIGIN: String="origin"
    val GOOGLEUSER: String="google_user"
    val USERS: String="users"
    val FACEBOOKUSER: String="fb_user"
    val USER: String="userTTT"
    val UID="uid"
    val FCM="fcm"
    val isDataSaved="isDataSaved"
    val LOOKINGFOR="lookingFor"
}
*/
